version: 2.1
jobs:
  build:
    working_directory: /temp
    docker: 
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-focal
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: 
          name: "Pull submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: 
          name: "List files"
          command: ls -lha
      - run: dotnet restore
      - run: dotnet build --configuration Release
