version: 2.1
jobs:
  unittest:
    working_directory: /temp
    docker: 
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-focal
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run: 
          name: "Pull core submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run: dotnet restore
      - run: dotnet build --configuration Release
      - run: dotnet test Tests/TestsUnit.csproj
  integrationtest:
    working_directory: /temp
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-focal
      - image: 'circleci/redis:6'
      - image: 'circleci/postgres:12'
        environment:
          POSTGRES_DB: speckle2_test
          POSTGRES_PASSWORD: speckle
          POSTGRES_USER: speckle
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NODE_ENV: test
      DATABASE_URL: 'postgres://speckle:speckle@localhost:5432/speckle2_test'
      PGDATABASE: speckle2_test
      PGUSER: speckle
      SESSION_SECRET: 'keyboard cat'
      STRATEGY_LOCAL: true
      CANONICAL_URL: 'http://localhost:3000'
    steps:
      - run:
        name: "Install node"
        command: |
          curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt-get install -y nodejs
      - run:
        name: "Checkout server"
        command: git clone https://github.com/specklesystems/Server.git server
      - run:
        name: "Install deps"
        command: cd server && npm install

      # - checkout
      # - run: 
      #     name: "Pull core submodules"
      #     command: |
      #       git submodule init
      #       git submodule update --remote
      # - run: dotnet restore
      # - run: dotnet build --configuration Release
      # - run: dotnet test Tests/TestsUnit.csproj